let form;
var prenailRequestSheet = "";

prenailRequestSheet += ""
prenailRequestSheet+= "<style>"
prenailRequestSheet+= ".page-header {"
prenailRequestSheet+= "display:flex"
prenailRequestSheet+= "}"
prenailRequestSheet+= ".wrapper {"
prenailRequestSheet+= "max-width: 900px;"
prenailRequestSheet+= "}"
prenailRequestSheet+= ".quote-info-wrapper {"
prenailRequestSheet+= "display:flex;"
prenailRequestSheet+= "flex-wrap: wrap;"
prenailRequestSheet+= "}"
prenailRequestSheet+= "label {"
prenailRequestSheet+= "margin: 5px;"
prenailRequestSheet+= "}"
prenailRequestSheet+= "</style>"
prenailRequestSheet+= "<div class='wrapper'>"
prenailRequestSheet+= "<header class='page-header' style = ''>"
prenailRequestSheet+= "<img src='https://www.earthimpressions.co.nz/wp-content/uploads/2021/07/Logo_ITM.jpg' />"
prenailRequestSheet+= "<h2>Prenail Estimate Request Sheet</h2></header>"
prenailRequestSheet+= "<table class=''>"
prenailRequestSheet+= "<tr><td>Client name:</td><td>Job name: </td></tr>"
prenailRequestSheet+= "<tr><td>Site Address: </td><td>Branch: </td></tr>"
prenailRequestSheet+= "<tr><td>Received By:</td><td>Sales Person/Rep</td></tr>"
prenailRequestSheet+= "<tr><td>Date Received:</td><td>Date Required:</td></tr>"
prenailRequestSheet+= "<tr><td>Builder:</td><td>Email:</td></tr>"
prenailRequestSheet+= "<tr><td>Quote reference:</td></tr></table>"
prenailRequestSheet+= "<div><label>Prenail Frames</label> <br />"
prenailRequestSheet+= "<label>Bottom Plates</label> <br />"
prenailRequestSheet+= "<label>Trusses / Balance of Roof / Cut Roof</label> <br />"
prenailRequestSheet+= "<label>Chimney framing</label> <br />"
prenailRequestSheet+= "<label>LVL Beams</label> <br />"
prenailRequestSheet+= "<label>Glulam Beams </label> <br />"
prenailRequestSheet+= "<label>Porch Posts</label> <br />"
prenailRequestSheet+= "<label>Verandah Posts </label> <br />"
prenailRequestSheet+= "<label>Enclosed balustrades interior</label> <br />"
prenailRequestSheet+= "<label>Enclosed balustrades exterior</label> <br />"
prenailRequestSheet+= "<label>Hip Boards</label> <br />"
prenailRequestSheet+= "<label>Verandah/Porch Beams - Exposed				</label> <br />"
prenailRequestSheet+= "<label>Beams in Soffit space</label> <br />"
prenailRequestSheet+= "<label>Metal Strap Bracing</label> <br />"
prenailRequestSheet+= "<label>Truss Bottom Chord Bracing - (Rondo) </label> <br />"
prenailRequestSheet+= "<label>Sub Floors</label> <br />"
prenailRequestSheet+= "<label>Flitch Beams </label> <br />"
prenailRequestSheet+= "<label>Mid Floors</label> <br />"
prenailRequestSheet+= "<label>Flitch Beams </label> <br />"
prenailRequestSheet+= "</div></div>"
