function doGet(e) {
  return HtmlService.createHtmlOutputFromFile('form');
}
function getIterator() {
  var id = "1fY-mHXQIxqW9l4sqFp2rogfd_-xD8WJNsHh7jc_phYc"
  var file = DriveApp.getFileById(id);
  var jobNumber = parseInt(file.getName(), 10);
  incrementIterator(jobNumber);
  return jobNumber
}
function incrementIterator(jobNumber) {
  var id = "1fY-mHXQIxqW9l4sqFp2rogfd_-xD8WJNsHh7jc_phYc"
  var file = DriveApp.getFileById(id)
  var current = jobNumber
  file.setName(jobNumber + 1)
}

function processForm(form) {
  try {
    var jobNumber = getIterator()
    var parentFolderId = "164tjlvUV_j_70zOorp9schQER60r767M"
    var clientFolderName = form.cRep;
    var parentFolder = DriveApp.getFolderById(parentFolderId)
    var folder, folders = parentFolder.getFoldersByName(clientFolderName);
    if (folders.hasNext()) {folder = folders.next();} else {folder = parentFolder.createFolder(clientFolderName);}
    var JobFolder = folder.createFolder("jobNumber: " + jobNumber)
    var valuesArray = [
      form.variable1,
      form.variable2,
      form.variable42,
      form.variable3,
      form.variable4,
      form.variable5,
      form.variable6,
      form.variable7,
      form.variable8,
      form.variable9,
      form.variable10,
      form.variable11,
      form.variable12,
      form.variable13,
      form.variable14,
      form.variable15,
      form.variable16,
      form.variable17,
      form.variable18,
      form.variable19,
      form.variable20,
      form.variable21,
      form.variable22,
      form.variable23,
      form.variable24,
      form.variable25,
      form.variable26,
      form.variable27,
      form.variable28,
      form.variable29,
      form.variable30,
      form.variable31,
      form.variable32,
      form.variable33,
      form.variable34,
      form.variable35,
      form.variable36,
      form.variable37
    ]
    var checkedArray = []
    for(var i = 0; i < valuesArray.length; i++) {
      if(valuesArray[i]) {
        checkedArray.push("checked")
      } else {
        checkedArray.push("")
      }
    }
    var location = []
    if(form.jobLocAuckland) {
      location.push("checked")
      location.push("")
    } else {
      location.push("")
      location.push("checked")
    }
    var contentSection1
    var contentSection2

    contentSection1 += "<!doctype html>"
    contentSection1 += "<head>"
    contentSection1 +="<style type='text/css'>"
    contentSection1 += "body {"
    contentSection1 +="text-align: -webkit-center;"
    contentSection1 +="background-color: #FFfFFF;"
    contentSection1 +="font-family: Sans-serif;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".firstCol {"
    contentSection1 +="width: 20%;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +="form {"
    contentSection1 +="width:1080px;"
    contentSection1 +="}"
    contentSection1 +=".address {"
    contentSection1 +="Height: 60px;"
    contentSection1 +="width: 350px;"
    contentSection1 +="margin-left:15px;"
    contentSection1 +="word-break:break-all;"
    contentSection1 +="}"
    contentSection1 +=".wrapper {"
    contentSection1 +="display: flex;"
    contentSection1 +="flex-flow: row wrap;"
    contentSection1 +="font-weight: bold;"
    contentSection1 +="text-align: center;"
    contentSection1 +=""
    contentSection1 +=""
    contentSection1 +="}"
    contentSection1 +=".header {"
    contentSection1 +="flex:1;"
    contentSection1 +="text-align: center;"
    contentSection1 +="min-width: 600px;"
    contentSection1 +="}"
    contentSection1 +=".main {"
    contentSection1 +="flex: 1;"
    contentSection1 +="}"
    contentSection1 +=".textbox {"
    contentSection1 +="/* float: right; */"
    contentSection1 +="}"
    contentSection1 +=".row {"
    contentSection1 +="display: flex;"
    contentSection1 +="flex-flow: row wrap;"
    contentSection1 +="text-align: center;"
    contentSection1 +="font-weight: normal;"
    contentSection1 +="font-size: 14;"
    contentSection1 +=""
    contentSection1 +="}"
    contentSection1 +=".checkboxContainer {"
    contentSection1 +="border: solid 3px black;"
    contentSection1 +="flex-flow: wrap;"
    contentSection1 +="width: 50%;"
    contentSection1 +="padding: 5px;"
    contentSection1 +=""
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".checkboxContainerheader {"
    contentSection1 +="background-color: grey;"
    contentSection1 +="padding: 5px"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".fullWidthContainer {"
    contentSection1 +="border: solid 3px black;"
    contentSection1 +="flex-flow: wrap;"
    contentSection1 +="width: 100%;"
    contentSection1 +="padding: 5px;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".pair {"
    contentSection1 +="display: flex;"
    contentSection1 +=""
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".right {"
    contentSection1 +="float: right;"
    contentSection1 +=""
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".uploadSection {"
    contentSection1 +="text-align: left;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".large {"
    contentSection1 +="height: 90px;"
    contentSection1 +="width: 90%;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".imagePair {"
    contentSection1 +="display: flex;"
    contentSection1 +=""
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".imageContainer {"
    contentSection1 +="flex-flow: wrap;"
    contentSection1 +="width: 50%;"
    contentSection1 +="padding: 5px;"
    contentSection1 +="}"
    contentSection1 +=".uploadRow {"
    contentSection1 +="display: flex;"
    contentSection1 +="text-align: center;"
    contentSection1 +="font-weight: normal;"
    contentSection1 +="font-size: 14;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".collapsible {"
    contentSection1 +="background-color: #777;"
    contentSection1 +="color: white;"
    contentSection1 +="cursor: pointer;"
    contentSection1 +="padding: 18px;"
    contentSection1 +="width: 100%;"
    contentSection1 +="border: none;"
    contentSection1 +="text-align: left;"
    contentSection1 +="outline: none;"
    contentSection1 +="font-size: 15px;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".active:after {"
    contentSection1 +="content: '\2796'; /* Unicode character for 'minus' sign (-) */"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +=".colContainer {"
    contentSection1 +="display: flex;"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +="/* Create two equal columns that sits next to each other */"
    contentSection1 +=".column {"
    contentSection1 +="flex: 50%;"
    contentSection1 +="padding: 10px;"
    contentSection1 +="}"
    contentSection1 +=".borderedTableItem {"
    contentSection1 +="border: 1px solid black;"
    contentSection1 +="}"
    contentSection1 +=".borderedTable {"
    contentSection1 +="border: 1px solid black;"
    contentSection1 +="width: 100%"
    contentSection1 +="}"
    contentSection1 +="</style>"
    contentSection1 +="</head>"
    contentSection1 +="<script>"
    contentSection1 +=""
    contentSection1 +="function updateUrl(url) {"
    contentSection1 +="var div = document.getElementById('output');"
    contentSection1 +="var form = document.getElementById('myForm');"
    contentSection1 +="div.innerHTML = '<p>'+url+'</p>';"
    contentSection1 +="form.style.display = 'none';"
    contentSection1 +="}"
    contentSection1 +=""
    contentSection1 +="</script>"
    contentSection1 +="<body>"
    contentSection1 +="<header>"
    contentSection1 +="<h3>Estimate Request</h3>"
    contentSection1 +="</header>"
    contentSection1 +="<div class='pair'>"
    contentSection1 +="<div class='checkboxContainer' style='border-right: 0px'>"
    contentSection1 +="<p>Store:"
    contentSection1 +="<select name=''>"
    contentSection1 +="<option value='volvo'>North Auckland</option>"
    contentSection1 +="<option value='saab'>East Tamaki</option>"
    contentSection1 +="<option value='fiat'>Rotorua</option>"
    contentSection1 +="<option value='audi'>Wellington</option>"
    contentSection1 +="</select>"
    contentSection1 +="</p>"
    contentSection1 +="<p>Store for Product Collection:"
    contentSection1 +="<select name=''>"
    contentSection1 +="<option value='volvo'>North Auckland</option>"
    contentSection1 +="<option value='saab'>East Tamaki</option>"
    contentSection1 +="<option value='fiat'>Rotorua</option>"
    contentSection1 +="<option value='audi'>Wellington</option>"
    contentSection1 +="</select>"
    contentSection1 +="</p>"
    contentSection1 +="</div>"
    contentSection1 +="<div class='checkboxContainer' style='border-left: 0px'>"
    contentSection1 +=""
    contentSection1 +="<p>Date: <input class='textbox right' name='' type='text' style='width: 50%;'></p>"
    contentSection1 +="<p>Tender Date: <input class='textbox right' name='' type='text' style='width: 50%;'></p>"
    contentSection1 +="</div>"
    contentSection1 +="</div>"
    contentSection1 +=""
    contentSection1 +="<form id='myForm' align='center' onsubmit='handleFormSubmit(this)'>"
    contentSection1 +="<div class='wrapper'>"
    contentSection1 +="<div class='main'>"
    contentSection1 +=""
    contentSection1 +="<table>"
    contentSection1 +="<tr>"
    contentSection1 +="<td class='checkboxZone'>"
    contentSection1 +="</td>"
    contentSection1 +="<td>"
    contentSection1 +="<button type='button' class='collapsible'>Section 1: Customers Details</button>"
    contentSection1 +="<div class='content'>"
    contentSection1 +="<div class='pair'>"
    contentSection1 +="<div class='checkboxContainer'>"
    contentSection1 +="<p class='row'>Account/Customers Name:<input class='textbox' type='text' placeholder='Account/Customers Name' ></p>"
    contentSection1 +="<p class='row'>Site Address:<textarea class='textbox address' name='' type='text' placeholder='Site Address'></textarea></p>"
    contentSection1 +="<p class='row'>Customers Account Number:<input class='textbox' name='' type='text' placeholder=''></p>"
    contentSection1 +="<p class='row'>Price file required<input name='' type='checkbox'></p>"
    contentSection1 +="<p class='row'>Account Manager:<input class='textbox' type='text' placeholder=''></p>"
    contentSection1 +=""
    contentSection1 +="</div>"
    contentSection1 +="<div class='checkboxContainer'>"
    contentSection1 +=""
    contentSection1 +="<p class='row'>Customer Contact Name:<input class='textbox' type='text' placeholder='Account/Customers Name' ></p>"
    contentSection1 +="<p class='row'>Customers Address:<textarea class='textbox address' name='' type='text' placeholder='Site Address'></textarea></p>"
    contentSection1 +="<p class='row'>Customers Phone:<input class='textbox' name='' type='text' placeholder=''></p>"
    contentSection1 +="<p class='row'>BUN Job Number:<input class='textbox' name='' type='text' placeholder=''></p>"
    contentSection1 +="<p class='row'>Template:"
    contentSection1 +="<select name=''>"
    contentSection1 +="<option value='volvo'>North Auckland</option>"
    contentSection1 +="<option value='saab'>East Tamaki</option>"
    contentSection1 +="<option value='fiat'>Rotorua</option>"
    contentSection1 +="<option value='audi'>Wellington</option>"
    contentSection1 +="</select>"
    contentSection1 +="</p>"
    contentSection1 +="</div>"
    contentSection1 +="</div>"
    contentSection1 +="</div>"
    contentSection1 +="</td>"
    contentSection1 +="</tr>"
    contentSection1 +="</div>"
    contentSection1 +="</form>"
    contentSection1 +="</body>"

    contentSection2 += "<!doctype html>"
    contentSection2 += "<head>"
    contentSection2 += "<style type='text/css'>"
    contentSection2 += "body {"
    contentSection2 += "text-align: -webkit-center;"
    contentSection2 += "background-color: #FFfFFF;"
    contentSection2 += "font-family: Sans-serif;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".firstCol {"
    contentSection2 += "width: 20%;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += "form {"
    contentSection2 += "width:1080px;"
    contentSection2 += "}"
    contentSection2 += ".address {"
    contentSection2 += "Height: 60px;"
    contentSection2 += "width: 350px;"
    contentSection2 += "margin-left:15px;"
    contentSection2 += "word-break:break-all;"
    contentSection2 += "}"
    contentSection2 += ".wrapper {"
    contentSection2 += "display: flex;"
    contentSection2 += "flex-flow: row wrap;"
    contentSection2 += "font-weight: bold;"
    contentSection2 += "text-align: center;"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "}"
    contentSection2 += ".header {"
    contentSection2 += "flex:1;"
    contentSection2 += "text-align: center;"
    contentSection2 += "min-width: 600px;"
    contentSection2 += "}"
    contentSection2 += ".main {"
    contentSection2 += "flex: 1;"
    contentSection2 += "}"
    contentSection2 += ".textbox {"
    contentSection2 += "/* float: right; */"
    contentSection2 += "}"
    contentSection2 += ".row {"
    contentSection2 += "display: flex;"
    contentSection2 += "flex-flow: row wrap;"
    contentSection2 += "text-align: center;"
    contentSection2 += "font-weight: normal;"
    contentSection2 += "font-size: 14;"
    contentSection2 += ""
    contentSection2 += "}"
    contentSection2 += ".checkboxContainer {"
    contentSection2 += "border: solid 3px black;"
    contentSection2 += "flex-flow: wrap;"
    contentSection2 += "width: 50%;"
    contentSection2 += "padding: 5px;"
    contentSection2 += ""
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".checkboxContainerheader {"
    contentSection2 += "background-color: grey;"
    contentSection2 += "padding: 5px"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".fullWidthContainer {"
    contentSection2 += "border: solid 3px black;"
    contentSection2 += "flex-flow: wrap;"
    contentSection2 += "width: 100%;"
    contentSection2 += "padding: 5px;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".pair {"
    contentSection2 += "display: flex;"
    contentSection2 += ""
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".right {"
    contentSection2 += "float: right;"
    contentSection2 += ""
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".uploadSection {"
    contentSection2 += "text-align: left;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".large {"
    contentSection2 += "height: 90px;"
    contentSection2 += "width: 90%;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".imagePair {"
    contentSection2 += "display: flex;"
    contentSection2 += ""
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".imageContainer {"
    contentSection2 += "flex-flow: wrap;"
    contentSection2 += "width: 50%;"
    contentSection2 += "padding: 5px;"
    contentSection2 += "}"
    contentSection2 += ".uploadRow {"
    contentSection2 += "display: flex;"
    contentSection2 += "text-align: center;"
    contentSection2 += "font-weight: normal;"
    contentSection2 += "font-size: 14;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".collapsible {"
    contentSection2 += "background-color: #777;"
    contentSection2 += "color: white;"
    contentSection2 += "cursor: pointer;"
    contentSection2 += "padding: 18px;"
    contentSection2 += "width: 100%;"
    contentSection2 += "border: none;"
    contentSection2 += "text-align: left;"
    contentSection2 += "outline: none;"
    contentSection2 += "font-size: 15px;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += ".active, .collapsible:hover {"
    contentSection2 += "background-color: #555;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += "/*"
    contentSection2 += ".content {"
    contentSection2 += "padding: 0 18px;"
    contentSection2 += "max-height: 0;"
    contentSection2 += "overflow: hidden;"
    contentSection2 += "transition: max-height 0.2s ease-out;"
    contentSection2 += "background-color: #f1f1f1;"
    contentSection2 += "} */"
    contentSection2 += ""
    contentSection2 += ".colContainer {"
    contentSection2 += "display: flex;"
    contentSection2 += "}"
    contentSection2 += ""
    contentSection2 += "/* Create two equal columns that sits next to each other */"
    contentSection2 += ".column {"
    contentSection2 += "flex: 50%;"
    contentSection2 += "padding: 10px;"
    contentSection2 += "}"
    contentSection2 += ".borderedTableItem {"
    contentSection2 += "border: 1px solid black;"
    contentSection2 += "}"
    contentSection2 += ".borderedTable {"
    contentSection2 += "border: 1px solid black;"
    contentSection2 += "width: 100%"
    contentSection2 += "}"
    contentSection2 += "</style>"
    contentSection2 += "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>"
    contentSection2 += ""
    contentSection2 += "</head>"
    contentSection2 += ""
    contentSection2 += "<body>"
    contentSection2 += "<form id='myForm' align='center' onsubmit='handleFormSubmit(this)'>"
    contentSection2 += "<div class='wrapper'>"
    contentSection2 += "<div class='main'>"
    contentSection2 += "<div class='pair'>"
    contentSection2 += "<div class='checkboxContainer' style='border-right: 0px'>"
    contentSection2 += "<p>Store:"
    contentSection2 += "<select name=''>"
    contentSection2 += "<option value='volvo'>North Auckland</option>"
    contentSection2 += "<option value='saab'>East Tamaki</option>"
    contentSection2 += "<option value='fiat'>Rotorua</option>"
    contentSection2 += "<option value='audi'>Wellington</option>"
    contentSection2 += "</select>"
    contentSection2 += "</p>"
    contentSection2 += "<p>Store for Product Collection:"
    contentSection2 += "<select name=''>"
    contentSection2 += "<option value='volvo'>North Auckland</option>"
    contentSection2 += "<option value='saab'>East Tamaki</option>"
    contentSection2 += "<option value='fiat'>Rotorua</option>"
    contentSection2 += "<option value='audi'>Wellington</option>"
    contentSection2 += "</select>"
    contentSection2 += "</p>"
    contentSection2 += "</div>"
    contentSection2 += "<div class='checkboxContainer' style='border-left: 0px'>"
    contentSection2 += ""
    contentSection2 += "<p>Date: <input class='textbox right' name='' type='text' style='width: 50%;'></p>"
    contentSection2 += "<p>Tender Date: <input class='textbox right' name='' type='text' style='width: 50%;'></p>"
    contentSection2 += "</div>"
    contentSection2 += "</div>"
    contentSection2 += ""
    contentSection2 += "<table>"
    contentSection2 += "<tr>"
    contentSection2 += "<td class='checkboxZone'>"
    contentSection2 += "<input type='checkbox' name='section2Required'></input>"
    contentSection2 += "</td>"
    contentSection2 += "<td>"
    contentSection2 += "<button type='button' class='collapsible'>Section 2: Plan Specifications - FOR QS USE</button>"
    contentSection2 += "<div class='content'>"
    contentSection2 += "<div class='colContainer'>"
    contentSection2 += "<div class='column'>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Foundations</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Reinforcing - Random Supply Only</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Blockwork incl of Retaining</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Concrete</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Rib Raft Pods & accessories</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Slab Insulation</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += ""
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Prenail Supplied Items</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Frames</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Trusses</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Roof Pack</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Metal Ceiling Batten</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += ""
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Random Framing</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Only if Prenail Not Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wall Framing</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Ceiling Pack</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Rafters</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Roof Pack</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += ""
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Timber Floor</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Sub Floor Framing</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Mid Floor Framing</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Flooring</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wet Area Flooring</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wet Area Underlay</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += ""
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Insulation - SUPPLY ONLY</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required Rating if diff to plan</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Sub Floor</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Mid Floor</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wall</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Ceiling</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Strapped Walls</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Acoustic</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Exterior Cladding</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required Rating if diff to plan</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Timber Fascia</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Brick (Qty per m2)</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Sheet</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Fibre Cement Weatherboard</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Timber Weatherboard</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Stone Cladding Substrate</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Other</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "</div>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<div class='column'>"
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Interior Lining</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Walls</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Ceiling</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wet Wall lining</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wet Ceiling lining</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Other</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Interior Doors</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Confirm Door height</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Door type	Y	Polycore</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Jambs Type</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</table>"
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Door Furniture</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Type</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Interior Finishings</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Skirting</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Architraves</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Timber Cornice</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Gib Cove</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Wet Areas</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Shelving</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Landscaping</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Decks - Pine</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Decks - Redwood</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Decks - Hardwood</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Decks - Composite</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Pergola</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Carport</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Timber Retaining Walls</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Concrete Patios</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "<br>"
    contentSection2 += ""
    contentSection2 += ""
    contentSection2 += "<table class='BorderedTable' style='border-collapse: collapse;'>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<th class='borderedTableItem'>Other Items</th>"
    contentSection2 += "<th class='borderedTableItem'><input type='checkbox'></th>"
    contentSection2 += "<th class='borderedTableItem'>Required</th>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Ply to Membrane Roof</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Ply to Shingle Roof</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Garage Door</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>PVC Spouting System</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>PVC Downpipes</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>Skylight/Suntubes</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "<tr class='borderedTableItem'>"
    contentSection2 += "<td class='borderedTableItem'>PVC Roofing</td>"
    contentSection2 += "<td class='borderedTableItem'><input type='checkbox'></td>"
    contentSection2 += "<td class='borderedTableItem'><input class='textbox' type='text'></td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "<br>"
    contentSection2 += "</div>"
    contentSection2 += "</div>"
    contentSection2 += "</div>"
    contentSection2 += "</td>"
    contentSection2 += "</tr>"
    contentSection2 += "</table>"
    contentSection2 += "</div>"
    contentSection2 += "</div>"
    contentSection2 += "</form>"
    contentSection2 += "</body>"




    var blob1 = Utilities.newBlob(contentSection1, "text/html", "text.html");
    var uploadedHTML1 = JobFolder.createFile("section1.html", contentSection1, MimeType.HTML);

    uploadedHTML1.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.EDIT);
    uploadedHTML1.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);


    var blob2 = Utilities.newBlob(contentSection2, "text/html", "text.html");
    var uploadedHTML2 = JobFolder.createFile("section2.html", contentSection2, MimeType.HTML);

    uploadedHTML2.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.EDIT);
    uploadedHTML2.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);


    var uploadableFiles = []
    var uploadedFiles = []

    if(form.myFile1.name) {uploadableFiles.push(form.myFile1)}
    if(form.myFile2.name) {uploadableFiles.push(form.myFile2)}
    if(form.myFile2extra1.name) {uploadableFiles.push(form.myFile2extra1)}
    if(form.myFile2extra2.name) {uploadableFiles.push(form.myFile2extra2)}
    if(form.myFile2extra3.name) {uploadableFiles.push(form.myFile2extra3)}
    if(form.myFile2extra4.name) {uploadableFiles.push(form.myFile2extra4)}
    if(form.myFile3.name) {uploadableFiles.push(form.myFile3)}
    if(form.myFile4.name) {uploadableFiles.push(form.myFile4)}

    if(uploadableFiles.length) {
      for( var iter = 0; iter < uploadableFiles.length; iter++) {
        var file = uploadableFiles[iter]
        var uploadedFile = JobFolder.createFile(file);
        uploadedFile.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.EDIT);
        uploadedFile.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
        uploadedFiles.push(uploadedFile);
      }
    }

    // Email body (output)
    var output = "Job Submitted successfully, Below are your file Links"
    if(uploadedFiles.length) {
      for(var it = 0; it < uploadedFiles.length; it++) {
        output += "<br> <a href='" + uploadedFiles[it].getUrl() + "'>Link to "+ uploadedFiles[it].getName() + "</a>";
      }
    }
    output += "<br> <a href='" + uploadedHTML1.getUrl() + "'>Link to section 1 as HTML </a>";
    output += "<br> <a href='" + uploadedHTML2.getUrl() + "'>Link to section 2 as HTML </a>";
    output += "<br> This is the job number "+ jobNumber;
    output += "<br> Job Client is "+ form.cClient;

    // email subjects
    var genericSubject = 'New job, number '+ jobNumber
    var detailingSubject = 'New job, number ' + jobNumber


    sendEmail('thekingliveson@gmail.com', contentSection1, output, detailingSubject) // email the quotes team


    return output
  } catch (error) {
    Logger.log(error.toString())
    return error.toString();
  }
}
function sendEmail(email, content, output, subject) {
  GmailApp.sendEmail(
    email,
    subject,
    '',
    {
      htmlBody: output
    });
  }
